INTYGFV-15592: Added total number of sick leaves to populated filters…
sklintyg/intygstjanst pull request #141
Opened 2023-05-09 12:54 UTC by mhornfeldt

… response and refactored filtering on protected person

2023-05-10 11:01 UTC, mww-sopra-steria requested changes
Nicely done! A few comments to look at before it is ready for merge.

2023-05-10 11:01 UTC, mww-sopra-steria commented on web/src/main/java/se/inera/intyg/intygstjanst/web/service/impl/PuFilterServiceImpl.java
> +                    if (filterProtectedPerson) {
The tests you found in Rehabstod needs to be covered here:
- testSekretessmarkeradIsIncludedWhenUserIsLakareAsRehabkoordinatorAndSignedTheIntyg
- testSekretessmarkeradIsExcludedWhenUserIsLakareAsRehabkoordinatorOnSameUnitButIsNotSigning

The rule is that only a doctor should see any protected patient if the doctor was the issuer of the sick leave certificate.

What do you think about a solution like this?
filterProtectedPerson change from boolean -> string. It contains the doctorId that we should allow to show protected patients for. If no doctorId is provided, no protected patients should be displayed/return. If a doctorId is provided it needs to match the doctorId on the IntygData.

filterProtectedPerson could change to something that describes the use a bit better. Don't have a great naming suggestion yet :-)

2023-05-10 13:30 UTC, mhornfeldt commented
> Nicely done! A few comments to look at before it is ready for merge.

Fixed!

2023-05-11 08:11 UTC, mww-sopra-steria approved these changes
Nice, approved!

2023-05-11 11:09 UTC, merged