INTYGFV-15642: Added new DB table REKO with related columns.
sklintyg/intygstjanst pull request #150
Opened 2023-05-17 09:40 UTC by ChrilleSigerhed

2023-05-17 12:02 UTC, mww-sopra-steria requested changes
Introduce RekoRepository as well!

2023-05-22 12:22 UTC, mww-sopra-steria requested changes
A few comments to consider.

2023-05-22 12:58 UTC, ChrilleSigerhed commented on persistence/src/test/java/se/inera/intyg/intygstjanst/persistence/model/dao/impl/RekoRepositoryTest.java
> +public class RekoRepositoryTest extends TestSupport {
Good idea, done!

2023-05-23 05:53 UTC, mww-sopra-steria approved these changes
Nice! Approved! You could rename an argument if you like, before merging... see comment.

2023-05-23 05:53 UTC, mww-sopra-steria commented on persistence/src/main/java/se/inera/intyg/intygstjanst/persistence/model/dao/RekoRepository.java
> +    List<Reko> findByPatientIdInAndCareUnitId(List<String> patientId, String careUnitId);
patientId -> patientIds

2023-05-23 06:27 UTC, merged