INTYGFV-15844: Implementation to ensure that messages cannot be sent …
sklintyg/intygstjanst pull request #174
Opened 2023-09-13 13:21 UTC by mikaelaromild1

…unless certificate is already sent.

2023-09-13 14:56 UTC, ChrilleSigerhed requested changes
Well done, looks great! Added comments related to the type of validationsErrors in your tests, maybe we should change it to final var for uniformly purposes?

2023-09-13 14:56 UTC, ChrilleSigerhed commented on web/src/test/java/se/inera/intyg/intygstjanst/web/integration/validator/SendMessageToRecipientValidatorTest.java
> +        List<String> validationErrors = validator.validate(buildOkMessage(PATIENT_CRN));
Maybe change this to ```final var``` intead of ```List<String>``` to match the rest of the implementation?

2023-09-13 14:56 UTC, ChrilleSigerhed commented on web/src/test/java/se/inera/intyg/intygstjanst/web/integration/validator/SendMessageToRecipientValidatorTest.java
> +        List<String> validationErrors = validator.validate(buildOkMessage(PATIENT_CRN));
Maybe change this to ```final var``` intead of ```List<String>``` to match the rest of the implementation?

2023-09-13 14:56 UTC, ChrilleSigerhed commented on web/src/test/java/se/inera/intyg/intygstjanst/web/integration/validator/SendMessageToRecipientValidatorTest.java
> +        List<String> validationErrors = validator.validate(buildOkMessage(PATIENT_CRN));
Maybe change this to ```final var``` intead of ```List<String>``` to match the rest of the implementation?

2023-09-14 11:37 UTC, mikaelaromild1 commented
Made changes according to our discussion.

2023-09-14 11:47 UTC, ChrilleSigerhed approved these changes
Well done!

2023-09-14 12:03 UTC, merged